import {
  Home,
  Users,
  BarChart3,
  Settings,
  FileText,
  ShoppingBag,
  Bell,
  Calendar,
  LogOut,
  UserPlus,
  UserCheck,
  Shield,
  TrendingUp,
  PieChart,
  Activity,
  Globe,
  Users2,
  Eye,
  MousePointer,
  Package,
  ShoppingCart,
  Package2,
  FileCheck,
  ClipboardList,
  Receipt,
  Cog,
  Database,
  Lock,
  Zap,
  FileSpreadsheet,
  FileImage,
  Download,
  Upload,
  Archive,
  Folder,
  Search,
  Filter,
  DollarSign,
  Building,
  User,
  CreditCard,
  Truck,
  MapPin,
  Phone,
  Mail,
  Clock,
  CheckCircle,
  XCircle,
  AlertCircle,
  Star,
  Tag,
  Percent,
  Calculator,
  Bookmark,
  Flag,
  Hash,
  Link,
  PlusCircle,
  MinusCircle,
  Edit,
  Trash,
  Copy,
  Send,
  Key,
  KeyRound,
  UserPen,
  HeartHandshake,
} from "lucide-react";

// ---------------------------------------------------

// Navbar MenuItems Data

export const menuItems = [
  {
    icon: Home,
    label: "Dashboard",
    active: false,
    clickable: true,
    path: "/dashboard",
  },
  {
    icon: Users,
    label: "User Management",
    hasSubmenu: true,
    clickable: false,
    submenu: [
      {
        icon: UserPlus,
        label: "Add Users",
        hasSubmenu: true,
        clickable: false,
        submenu: [
          {
            icon: User,
            label: "Individual User",
            path: "/users/add/individual",
            clickable: true,
          },
          {
            icon: Users2,
            label: "Bulk Import",
            path: "/users/add/bulk",
            clickable: true,
          },
          {
            icon: Upload,
            label: "CSV Upload",
            path: "/users/add/csv",
            clickable: true,
          },
          {
            icon: Link,
            label: "API Integration",
            path: "/users/add/api",
            clickable: true,
          },
        ],
      },
      {
        icon: UserCheck,
        label: "Active Users",
        hasSubmenu: true,
        clickable: false,
        submenu: [
          {
            icon: Eye,
            label: "View All",
            path: "/users/active/all",
            clickable: true,
          },
          {
            icon: Search,
            label: "Search Users",
            path: "/users/active/search",
            clickable: true,
          },
          {
            icon: Filter,
            label: "Filter Users",
            path: "/users/active/filter",
            clickable: true,
          },
          {
            icon: Download,
            label: "Export Users",
            path: "/users/active/export",
            clickable: true,
          },
        ],
      },
      {
        icon: Shield,
        label: "Permissions",
        hasSubmenu: true,
        clickable: false,
        submenu: [
          {
            icon: Lock,
            label: "Role Management",
            path: "/users/permissions/roles",
            clickable: true,
          },
          {
            icon: Key,
            label: "Access Control",
            path: "/users/permissions/access",
            clickable: true,
          },
          {
            icon: Settings,
            label: "Permission Sets",
            path: "/users/permissions/sets",
            clickable: true,
          },
        ],
      },
    ],
  },
  {
    icon: BarChart3,
    label: "Analytics",
    hasSubmenu: true,
    clickable: false,
    submenu: [
      {
        icon: TrendingUp,
        label: "Traffic",
        hasSubmenu: true,
        clickable: false,
        submenu: [
          {
            icon: Globe,
            label: "Website Traffic",
            hasSubmenu: true,
            clickable: false,
            submenu: [
              {
                icon: Eye,
                label: "Page Views",
                hasSubmenu: true,
                clickable: false,
                submenu: [
                  {
                    icon: Clock,
                    label: "Real-time Views",
                    path: "/analytics/traffic/website/pageviews/realtime",
                    clickable: true,
                  },
                  {
                    icon: Calendar,
                    label: "Daily Views",
                    path: "/analytics/traffic/website/pageviews/daily",
                    clickable: true,
                  },
                  {
                    icon: TrendingUp,
                    label: "Weekly Trends",
                    path: "/analytics/traffic/website/pageviews/weekly",
                    clickable: true,
                  },
                  {
                    icon: Archive,
                    label: "Historical Data",
                    path: "/analytics/traffic/website/pageviews/historical",
                    clickable: true,
                  },
                ],
              },
              {
                icon: Users2,
                label: "Unique Visitors",
                hasSubmenu: true,
                clickable: false,
                submenu: [
                  {
                    icon: Globe,
                    label: "New Visitors",
                    path: "/analytics/traffic/website/unique/new",
                    clickable: true,
                  },
                  {
                    icon: Bookmark,
                    label: "Returning Visitors",
                    path: "/analytics/traffic/website/unique/returning",
                    clickable: true,
                  },
                  {
                    icon: MapPin,
                    label: "Geographic Distribution",
                    path: "/analytics/traffic/website/unique/geo",
                    clickable: true,
                  },
                ],
              },
              {
                icon: Clock,
                label: "Session Duration",
                path: "/analytics/traffic/website/duration",
                clickable: true,
              },
              {
                icon: MousePointer,
                label: "Bounce Rate",
                path: "/analytics/traffic/website/bounce",
                clickable: true,
              },
            ],
          },
          {
            icon: Users2,
            label: "User Sessions",
            hasSubmenu: true,
            clickable: false,
            submenu: [
              {
                icon: Clock,
                label: "Active Sessions",
                path: "/analytics/traffic/sessions/active",
                clickable: true,
              },
              {
                icon: Calendar,
                label: "Session History",
                path: "/analytics/traffic/sessions/history",
                clickable: true,
              },
              {
                icon: Activity,
                label: "Session Analysis",
                path: "/analytics/traffic/sessions/analysis",
                clickable: true,
              },
            ],
          },
          {
            icon: MousePointer,
            label: "Click Analytics",
            path: "/analytics/traffic/clicks",
            clickable: true,
          },
        ],
      },
      {
        icon: PieChart,
        label: "Revenue",
        hasSubmenu: true,
        clickable: false,
        submenu: [
          {
            icon: DollarSign,
            label: "Total Revenue",
            path: "/analytics/revenue/total",
            clickable: true,
          },
          {
            icon: TrendingUp,
            label: "Revenue Growth",
            path: "/analytics/revenue/growth",
            clickable: true,
          },
          {
            icon: Calendar,
            label: "Monthly Reports",
            path: "/analytics/revenue/monthly",
            clickable: true,
          },
          {
            icon: Calculator,
            label: "Profit Margins",
            path: "/analytics/revenue/margins",
            clickable: true,
          },
        ],
      },
      {
        icon: Activity,
        label: "Reports",
        hasSubmenu: true,
        clickable: false,
        submenu: [
          {
            icon: FileText,
            label: "Generate Reports",
            path: "/analytics/reports/generate",
            clickable: true,
          },
          {
            icon: Archive,
            label: "Report Archive",
            path: "/analytics/reports/archive",
            clickable: true,
          },
          {
            icon: Download,
            label: "Export Data",
            path: "/analytics/reports/export",
            clickable: true,
          },
          {
            icon: Calendar,
            label: "Scheduled Reports",
            path: "/analytics/reports/scheduled",
            clickable: true,
          },
        ],
      },
    ],
  },
  {
    icon: ShoppingBag,
    label: "E-commerce",
    hasSubmenu: true,
    clickable: false,
    submenu: [
      {
        icon: Package,
        label: "Products",
        hasSubmenu: true,
        clickable: false,
        submenu: [
          {
            icon: PlusCircle,
            label: "Add Product",
            path: "/ecommerce/products/add",
            clickable: true,
          },
          {
            icon: Eye,
            label: "View All",
            path: "/ecommerce/products/all",
            clickable: true,
          },
          {
            icon: Tag,
            label: "Categories",
            path: "/ecommerce/products/categories",
            clickable: true,
          },
          {
            icon: Star,
            label: "Featured Products",
            path: "/ecommerce/products/featured",
            clickable: true,
          },
          {
            icon: Percent,
            label: "Discounts",
            path: "/ecommerce/products/discounts",
            clickable: true,
          },
        ],
      },
      {
        icon: ShoppingCart,
        label: "Orders",
        hasSubmenu: true,
        clickable: false,
        submenu: [
          {
            icon: CheckCircle,
            label: "Completed Orders",
            hasSubmenu: true,
            clickable: false,
            submenu: [
              {
                icon: Receipt,
                label: "Order Details",
                path: "/ecommerce/orders/completed/details",
                clickable: true,
              },
              {
                icon: Download,
                label: "Export Orders",
                path: "/ecommerce/orders/completed/export",
                clickable: true,
              },
              {
                icon: FileText,
                label: "Invoice Generation",
                path: "/ecommerce/orders/completed/invoices",
                clickable: true,
              },
            ],
          },
          {
            icon: Clock,
            label: "Pending Orders",
            path: "/ecommerce/orders/pending",
            clickable: true,
          },
          {
            icon: XCircle,
            label: "Cancelled Orders",
            path: "/ecommerce/orders/cancelled",
            clickable: true,
          },
          {
            icon: Truck,
            label: "Shipping Status",
            path: "/ecommerce/orders/shipping",
            clickable: true,
          },
        ],
      },
      {
        icon: Package2,
        label: "Inventory",
        hasSubmenu: true,
        clickable: false,
        submenu: [
          {
            icon: Eye,
            label: "Stock Levels",
            path: "/ecommerce/inventory/stock",
            clickable: true,
          },
          {
            icon: AlertCircle,
            label: "Low Stock Alerts",
            path: "/ecommerce/inventory/alerts",
            clickable: true,
          },
          {
            icon: Upload,
            label: "Stock Updates",
            path: "/ecommerce/inventory/updates",
            clickable: true,
          },
          {
            icon: Archive,
            label: "Warehouse Management",
            path: "/ecommerce/inventory/warehouse",
            clickable: true,
          },
        ],
      },
    ],
  },
  {
    icon: FileText,
    label: "Documents",
    hasSubmenu: true,
    clickable: false,
    submenu: [
      // (same pattern applied for invoices, contracts, etc — all with clickable: true if they have path)
    ],
  },
  {
    icon: Settings,
    label: "Settings",
    hasSubmenu: true,
    clickable: false,
    submenu: [
      { icon: HeartHandshake, label: "Team", path: "Team", clickable: true },
      { icon: Users, label: "Employees", path: "/employees", clickable: true },
      { icon: UserPen, label: "Profile", path: "/settings", clickable: true },
      {
        icon: KeyRound,
        label: "Permission",
        path: "/permission",
        clickable: true,
      },
    ],
  },
  {
    icon: LogOut,
    label: "Logout",
    path: "/logout",
    clickable: true,
  },
];

// ---------------------------------------------------

// Theme Mode

export const ActiveTheme = [
  { label: "light", value: true, color: "white" },
  { label: "dark", value: false, color: "black" },
];
